name: Install dependencies

description: 'Install dependencies'

inputs:
  fetch-repo:
    description: 'The repository name that needs to be fetched'
    # default: ${{ github.workflow == 'Automatically update NVDA.po' && 'nvda' || 'nvdaL10n' }}
    default: ${{ contains(github.workflow, 'Addon') && 'nvdaL10n' || 'nvda' }}
  ref:
    description: 'Branch name that needs to be checked out'
  submodules:
    description: 'Whether to checkout submodules'
    default: true
  Download-gettext:
    description: 'Whether to Download gettext'
    default: false
  set-variable:
    description: 'Whether to Set cache variables'
    default: false

runs:
  using: "composite"

  steps:
    - name: Checkout ${{ inputs.fetch-repo }} repository
      uses: actions/checkout@v6
      with:
        repository: nvaccess/${{ inputs.fetch-repo }}
        ref: ${{ inputs.ref }}
        submodules: ${{ inputs.submodules }}
        path: ${{ github.workspace }}/Tools/${{ inputs.fetch-repo }}
    - name: Cache gettext
      id: cache-gettext
      if: ${{ inputs.Download-gettext == 'true' }}
      uses: actions/cache@v5
      with:
        path: ${{ github.workspace }}/PotXliff/Temp/gettext.zip
        key: gettext.zip
    - name: Download gettext
      if: ${{ inputs.Download-gettext == 'true' && steps.cache-gettext.outputs.cache-hit != 'true' }}
      uses: carlosperate/download-file-action@v2
      with:
        file-url: https://github.com/mlocati/gettext-iconv-windows/releases/download/v0.24-v1.17/gettext0.24-iconv1.17-static-32.zip
        file-name: gettext.zip
        location: ${{ github.workspace }}/PotXliff/Temp
        sha256: c14d844f4950e14189fe47795700172f019ec2f5430bfa068a7a909ff784f45c
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Set cache variables
      if: ${{ inputs.set-variable == 'true' }}
      shell: pwsh
      run: |
        echo "VSCMD_SKIP_SENDTELEMETRY=1" >> $env:GITHUB_ENV
        echo "SCONS_CACHE_MSVC_CONFIG=${{ github.workspace }}\Tools\NVDA\.scons_msvc_cache.json" >> $env:GITHUB_ENV
        echo "SCONS_CACHE_KEY=scons_msvc_cache-$env:RUNNER_OS-$env:ImageVersion" >> $env:GITHUB_ENV
    - name: Create Python virtual environment
      shell: cmd
      run: |
        echo UV_MANAGED_PYTHON=true>> "%GITHUB_ENV%"
        uv --managed-python --directory "${{ github.workspace }}\Tools\${{ inputs.fetch-repo }}" sync
