name: Automatically update NVDA.po

on:
  push:
    branches:
      - "20*"
    paths:
      - 'Translation/LC_MESSAGES/*.po'
  schedule:
    - cron: '0 0,3,6,9 * * 1-5'
    - cron: '0 11 * * *'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  Check-NVDA-Repository-Update:
    name: Check NVDA repository update
    if: ${{ vars.Run_CheckPot_Workflow }}
    runs-on: ubuntu-latest
    outputs:
      has_update: ${{ steps.check_update.outputs.has_update }}
    steps:
      - name: Get current SHA
        id: get_current_sha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(curl -sf -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/nvaccess/nvda/branches/master)
          current_sha=$(echo "$response" | jq -r '.commit.sha')
          echo "current_sha=$current_sha" >> $GITHUB_OUTPUT
          echo "CACHE_KEY=nvda-sha-$current_sha" >> $GITHUB_ENV
      - name: Check SHA cache
        id: cache_sha
        uses: actions/cache@v5
        with:
          path: .sha_cache
          key: ${{ env.CACHE_KEY }}
          lookup-only: true
      - name: Determine update status
        id: check_update
        run: |
          if [[ "${{ steps.cache_sha.outputs.cache-hit }}" == 'true' ]]; then
            echo "Cache hit, no updates."
            echo "has_update=false" >> $GITHUB_OUTPUT
          else
            echo "Cache miss, new updates."
            echo "has_update=true" >> $GITHUB_OUTPUT
            mkdir -p .sha_cache
            echo "${{ steps.get_current_sha.outputs.current_sha }}" > .sha_cache/latest_sha
            echo "Cached SHA: $(cat .sha_cache/latest_sha)"
          fi

  Determine-Branch:
    name: Determine branch
    if: ${{ vars.Run_CheckPot_Workflow }}
    uses: ./.github/workflows/DetermineBranch.yaml
    secrets: inherit

  Update-NVDA-po:
    name: Update NVDA.po
    needs: 
      - Check-NVDA-Repository-Update
      - Determine-Branch
    if: ${{ needs.Check-NVDA-Repository-Update.outputs.has_update == 'true' }}
    runs-on: windows-latest
    env:
      branch: ${{ needs.Determine-Branch.outputs.branch }}
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ env.branch }}
      - name: Install dependencies
        uses: ./.github/actions/InstallDependencies
        with:
          fetch-repo: nvda
          ref: master
          submodules: true
          Download-gettext: true
          set-variable: true
      - name: SCons MSVC Cache
        uses: actions/cache@v5
        with:
          path: ${{ env.SCONS_CACHE_MSVC_CONFIG }}
          key: ${{ env.SCONS_CACHE_KEY }}
      - name: Run CheckPot.ps1
        run: .github/Scripts/CheckPot.ps1
      - name: Upload Output
        uses: actions/upload-artifact@v7
        with:
          name: NVDA.pot
          path: ${{ github.workspace }}/Tools/NVDA/output/*
