name: Update Addons Translations from Crowdin

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      Addon_ID:
        description: 'Add-on ID, multiple separated by spaces(optional)'
        required: false
concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  Determine-Branch:
    name: Determine branch
    if: ${{ vars.Run_Addon_Translations_Workflow }}
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.Determine_branch.outputs.Branch }}
    steps:
      - name: Determine branch name
        id: Determine_branch
        uses: nvdacn/zh_CN_Translation/.github/actions/DetermineBranch@Uploads

  Update-Addon-Translations:
    name: Update addon translations from Crowdin
    needs: Determine-Branch
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ needs.Determine-Branch.outputs.branch }}
      - name: Install dependencies
        uses: ./.github/actions/InstallDependenciesForAddon
      - name: Configure environment
        shell: pwsh
        run: |
          $CrowdinToken = "${{ secrets.NVDA_CROWDIN }}"
          $CrowdinToken | Out-File -FilePath ~/.nvda_crowdin -Encoding ascii
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Fetch translations
        env:
          AddonID: ${{ github.event.inputs.Addon_ID }}
        run: .github/Scripts/UpdateAddonTranslations.ps1
      - name: Commit & Push
        shell: pwsh
        run: |
          git diff --cached --quiet
          if ($LASTEXITCODE -ne 0) {
              git commit -m "更新插件翻译（从 Crowdin）"
              git pull --rebase
              git push
          } else {
              Write-Host "No changes to commit, skipping commit and push."
          }
