name: Update NVDA Translations from Crowdin

on:
  workflow_dispatch:

env:
  crowdinAuthToken: ${{ secrets.NVDA_CROWDIN }}
  GH_TOKEN: ${{ github.token }}
  BRANCH: Uploads

jobs:
  Update-Translations:
    name: Update translations
    if: ${{ vars.Run_NVDA_Translations_Workflow }}
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ env.BRANCH }}
      - name: Install dependencies
        uses: ./.github/actions/InstallDependencies
      - name: Update Translations
        run: |
          ${{ github.workspace }}/L10nUtilTools.bat DLA
          git add --update Translation
      - name: Commit & Push
        shell: pwsh
        run: |
          git diff --cached --quiet
          if ($LASTEXITCODE -ne 0) {
              git commit -m "更新翻译（从 Crowdin）"
              git pull --rebase
              git push
              gh workflow run build.yaml --ref ${{ env.BRANCH }} --repo ${{ github.repository }}
          } else {
              Write-Host "No changes to commit, skipping commit and push."
          }
