name: Update Addons Translations from Crowdin

on:
  workflow_dispatch:
    inputs:
      Addon_ID:
        description: 'Add-on ID, multiple separated by spaces(optional)'
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  Determine-Branch:
    name: Determine branch
    if: ${{ vars.Run_Addon_Translations_Workflow }}
    uses: ./.github/workflows/DetermineBranch.yaml
    secrets: inherit

  Update-Addon-Translations:
    name: Update addon translations from Crowdin
    needs: Determine-Branch
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ needs.Determine-Branch.outputs.branch }}
      - name: Install dependencies
        uses: ./.github/actions/InstallDependencies
      - name: Fetch translations
        env:
          AddonID: ${{ github.event.inputs.Addon_ID }}
          crowdinAuthToken: ${{ secrets.NVDA_CROWDIN }}
        run: .github/Scripts/UpdateAddonTranslations.ps1
      - name: Commit & Push
        shell: pwsh
        run: |
          git diff --cached --quiet
          if ($LASTEXITCODE -ne 0) {
              git commit -m "更新插件翻译（从 Crowdin）"
              git pull --rebase
              git push
          } else {
              Write-Host "No changes to commit, skipping commit and push."
          }
