name: Upload NVDA translations to Crowdin

on:
  push:
    branches:
      - "Uploads"
    paths:
      - 'Translation/LC_MESSAGES/*.po'
      - 'Translation/user_docs/*.xliff'

env:
  crowdinAuthToken: ${{ secrets.NVDA_CROWDIN }}
  GH_TOKEN: ${{ github.token }}
  GITHUB_EVENT_BEFORE: ${{ github.event.before }}

jobs:
  Process-Translations:
    name: Upload translation to Crowdin
    if: ${{ vars.Run_NVDA_Translations_Workflow }}
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: ./.github/actions/InstallDependencies
      - name: Process Translations
        shell: pwsh
        run: |
          .github/Scripts/UploadToCrowdin.ps1 -TranslationType "NVDA"
      - name: Commit & Push
        shell: pwsh
        run: |
          git diff --cached --quiet
          if ($LASTEXITCODE -ne 0) {
              git commit -m "更新已上传的翻译文件（从 Crowdin）"
              git pull --rebase
              git push origin ${{ github.ref_name }}
              gh workflow run build.yaml --ref ${{ github.ref_name }} --repo ${{ github.repository }}
          } else {
              Write-Host "No changes to commit, skipping commit and push."
          }
