name: Upload Addon translations to Crowdin

on:
  push:
    branches:
      - '20*'
    paths:
      - 'Translation/Addons/**'

env:
  crowdinAuthToken: ${{ secrets.NVDA_CROWDIN }}
  GH_TOKEN: ${{ github.token }}
  GITHUB_EVENT_BEFORE: ${{ github.event.before }}

jobs:
  Process-Translations:
    name: Upload translation to Crowdin
    if: ${{ vars.Run_Addon_Translations_Workflow }}
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: ./.github/actions/InstallDependencies
      - name: Process Translations
        id: check-changes
        shell: pwsh
        run: |
          .github/Scripts/UploadToCrowdin.ps1 -TranslationType "Addon"
      - name: Manually trigger UpdateAddonTranslations workflow
        if: steps.check-changes.outputs.has_changes == 'true'
        run: |
          gh workflow run UpdateAddonTranslations.yaml --ref ${{ github.ref_name }} --repo ${{ github.repository }}
